version: '3'

services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile_dev

    volumes:
      - ./backend:/workspace:cached
      - ~/.gitconfig:/root/.gitconfig

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    expose:
      - 8000

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile_dev

    volumes:
      - ./frontend:/workspace:cached
      - ~/.gitconfig:/root/.gitconfig

    expose:
      - 3333

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  rabbitmq:
    image: rabbitmq
    restart: unless-stopped

volumes:
  postgres-data:
